name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_KENNY }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  deploy-vercel-preview:
    name: Deploy vercel preview
    runs-on: ubuntu-latest

    steps:
      - name: test-dir
        run: echo ${{ GITHUB_REF_NAME }}
